#!/bin/bash
#---------------------------------------------------------------------------------
#  Create_Movie_Trajectories                   Daniel Hollas, 2014

#-This simple script generates and executes a set of dynamical trajectories using ABIN.
#-It uses geometries from xyz movie for initial conditions.
#-The geometries maybe generated by PickGeoms.sh
#-The trajectories are executed and stored in $folder
# Files needed in this folder: r.abin,input.in
# MyIRandom program should be in your $PATH.
# Also folder $pot (e.g. G09) is needed.
#---------------------------------------------------------------------------------

#######-----SETUP---#############
input=input.in
# following variables can be determined automatically from input for SH runs
# for classical AIMD, set initialstate and nstate equal to 1
initialstate=$(awk -F"[,=]" '{if($1=="istate_init")print $2}' $input) #initial state for SH
nstate=$(awk -F"[,=]" '{if($1=="nstate")print $2}' $input)   #total number of electronic states
natom=$(awk -F"[,=]" '{if($1=="natom")print $2}' $input) #number of atoms

isample=1  	        # initial number of traj
nsample=1	        # number of trajectories
folder=CAS22.$initialstate  # name of the directory
molname=water            # for the name of the job in the queue
abinexe=/home/$USER/bin/abin.dev  # path to abin binary
movie="./geoms.xyz"  # path to wigner "trajectories"
irandom0=10061989       # random seed, set negative for random seed based on time
pot="MOLPRO"            # folder with ab initio bash script
#submit="qsub -q aq"    # comment this line if you don't want to submit to queue yet

##########END OF SETUP##########

echo "initial_state nstate natom"
echo $initialstate $nstate $natom

#- NO MORE MODIFICATION USUALLY NEEDED
inputcheck=$(awk '{if($1=="&general"){print NR;exit 0}}' $input)
if [[ $inputcheck -ne 1 ]];then
	echo "First line in file $input must be \"&general\"!"
	echo "Exiting now..."
	exit 1
fi

#--------------------generation of random numbers--------------------------------
echo "Generating $nsample random integers."
MyIRandom $irandom0 $nsample > iran.dat
if [[ $? -ne "0" ]];then
   echo "Error during random number generation.Exiting now..."
   exit 1
fi
#--------------------------------------------------------------------------------

mkdir -p $folder
cp iseed0 $input $folder

offset=0
while [[ $i -le $nsample ]];do

   let offset=offset+natom2

   if [[ -e $folder/TRAJ.$i ]];then
	echo "Trajectory number $i already exists!!Please, delete it."
	echo "Exiting..."
	exit 1
   #	rm -r $folder/TRAJ.$i
   fi

   mkdir $folder/TRAJ.$i
   cp -r $pot $folder/TRAJ.$i

#-----the same initial geometries for simulations from all initial states----

   head -$offset $movie | tail -$natom2 > $folder/TRAJ.$i/mini.dat

   irandom=`head -$i iran.dat |tail -1`

   echo '&general' > $folder/TRAJ.$i/input.in
   echo "irandom=$irandom,         ! random seed">>$folder/TRAJ.$i/input.in
   grep -v -e irandom -e '&general' $input >> $folder/TRAJ.$i/input.in

   cd $folder/TRAJ.$i/

#------------sending on scratch-------------------------------------------
cat > r.$molname.$initialstate.$i << EOF
#!/bin/bash
ABINEXE=$abinexe
JOBNAME=ABIN.$molname.$initialstate.$i.\$\$
INPUTPARAM=input.in
INPUTGEOM=mini.dat
OUTPUT=output
EOF

   grep -v -e 'ABINEXE=' -e "JOBNAME=" -e "INPUTPARAM=" -e "INPUTGEOM=" ../../r.abin >>r.$molname.$initialstate.$i

#---------------------------------------------------------------------------
   if [[ ! -z $submit ]];then
      $submit -cwd r.$molname.$initialstate.$i
   fi

   cd ../..
   let i++

done

