! D. Hollas 2014

! Program for generation of ABIN restart files from:
! 1) input coordinates and velocities as xyz files.
! 2) Coordinates and velocities from Wigner Transform from MOLPRO.

! It should be called within script create_trajectories.sh

! In mode 1, we expect coordinates in Angstroms and velocities in atomic units.

! In mode 2, we expect input generated by script wigner_sampling.sh
! As an input, we need files FMSINPOUT/Geometry.dat and FMSTRAJS/Traj.xx
! Atom masses are determined from the library of elements.
! Atom names are taken from FMSINPOUT/Geometry.dat.
! This will typically be: FMSINPOUT/geometry.xyz

! Call as:
! 1)   ./make_restart -mov coords.xyz veloc.dat nstate istate_init
! 2)   ./make_restart -wig FMSINPOUT/Geometry.dat FMSTRAJS/Traj.xx nstate istate_init

module mod_restart
   implicit none
   real*8,parameter    :: ANG=1.8897d0
   integer,parameter   :: charlength=100
   real*8, allocatable :: x(:), y(:), z(:)
   real*8, allocatable :: vx(:), vy(:), vz(:)
   real*8, allocatable :: xwig(:), p(:), mass(:)
   character(len=2), allocatable :: atom(:)

contains

   subroutine alloc(natom)
   integer, intent(in) :: natom

   allocate( x(natom) )
   allocate( y(natom) )
   allocate( z(natom) )
   allocate( vx(natom) )
   allocate( vy(natom) )
   allocate( vz(natom) )
   allocate( atom(natom) )
   allocate( mass(natom) )
   allocate( xwig(natom*3) )
   allocate( p(natom*3) )

   end subroutine alloc

   subroutine mass_init(natom,names,am)
      implicit none
      character*2, intent(in) :: names(:)
      real*8, intent(out)     :: am(:) 
      integer, intent(in)     :: natom
      real*8,parameter        :: mu=1823.d0
      integer :: i

      do i=1,natom
       if(names(i).eq.'H')then
        am(i)=1.008d0
       else if(names(i).eq.'H1')then
        am(i)=1.00782503207d0 
       else if(names(i).eq.'H2'.or.names(i).eq.'D')then
        am(i)=2.01410177785d0
       else if(names(i).eq.'O')then
        am(i)=15.999d0
       else if (names(i).eq.'S')then
        am(i)=32.06d0
       else if (names(i).eq.'SE')then
        am(i)=78.971d0
       else if (names(i).eq.'TE')then
        am(i)=127.60d0
       else if (names(i).eq.'N')then
        am(i)=14.007d0
       else if (names(i).eq.'P')then
        am(i)=30.973761998d0
       else if (names(i).eq.'AS')then
        am(i)=74.921595d0
       else if (names(i).eq.'SB')then
        am(i)=121.760d0
       else if (names(i).eq.'BI')then
        am(i)=208.98040d0
       else if (names(i).eq.'F')then
        am(i)=18.998403163d0
       else if (names(i).eq.'CL')then
        am(i)=35.45d0
       else if (names(i).eq.'BR')then
        am(i)=79.904d0
       else if (names(i).eq.'I')then
        am(i)=126.90447d0
       else if (names(i).eq.'LI')then
        am(i)=6.94d0
       else if (names(i).eq.'NA')then
        am(i)=22.98976928d0
       else if (names(i).eq.'K')then
        am(i)=39.0983d0
       else if (names(i).eq.'BE')then
        am(i)=9.0121831d0
       else if (names(i).eq.'MG')then
        am(i)=24.305d0
       else if (names(i).eq.'CA')then
        am(i)=40.078d0
       else if (names(i).eq.'B')then
        am(i)=10.81d0
       else if (names(i).eq.'AL')then
        am(i)=26.9815385d0
       else if (names(i).eq.'C')then
        am(i)=12.0110d0
       else if (names(i).eq.'SI')then
        am(i)=28.085d0
       else if (names(i).eq.'GE')then
        am(i)=72.630d0
       else if (names(i).eq.'SN')then
        am(i)=118.710d0
       else if (names(i).eq.'PB')then
        am(i)=207.2d0
       else if (names(i).eq.'HE')then
        am(i)=4.002602d0
       else if (names(i).eq.'NE')then
        am(i)=20.1797d0
       else if (names(i).eq.'AR')then
        am(i)=39.948d0
       else if (names(i).eq.'KR')then
        am(i)=83.798d0
       else if (names(i).eq.'XE')then
        am(i)=131.293d0
       else if (names(i).eq.'FE')then
        am(i)=55.845d0
       else if (names(i).eq.'TI')then
        am(i)=47.867d0
       else if (names(i).eq.'V')then
        am(i)=50.9415d0
       else if (names(i).eq.'CR')then
        am(i)=51.9961d0
       else if (names(i).eq.'MN')then
        am(i)=54.938044d0
       else if (names(i).eq.'CO')then
        am(i)=58.933194d0
       else if (names(i).eq.'NI')then
        am(i)=58.6934d0
       else if (names(i).eq.'CU')then
        am(i)=63.546d0
       else if (names(i).eq.'ZN')then
        am(i)=65.38d0
       else if (names(i).eq.'AG')then
        am(i)=107.8682d0
       else if (names(i).eq.'AU')then
        am(i)=196.966569d0
       else if (names(i).eq.'PT')then
        am(i)=195.084d0
       else if (names(i).eq.'CD')then
        am(i)=112.414d0
       else if (names(i).eq.'HG')then
        am(i)=200.592d0
       else if (names(i).eq.'U')then
        am(i)=238.02891d0
       else if (names(i).eq.'TL')then
        am(i)=204.38d0
       else if (names(i).eq.'BA')then
        am(i)=137.327d0
       else if (names(i).eq.'CE')then
        am(i)=140.116d0
       else if (names(i).eq.'CS')then
        am(i)=132.90545196d0
       else if (names(i).eq.'DY')then
        am(i)=162.500d0
       else if (names(i).eq.'ER')then
        am(i)=167.259d0
       else if (names(i).eq.'EU')then
        am(i)=151.964d0
       else if (names(i).eq.'GD')then
        am(i)=157.25d0
       else if (names(i).eq.'GA')then
        am(i)=69.723d0
       else if (names(i).eq.'HF')then
        am(i)=178.49d0
       else if (names(i).eq.'HO')then
        am(i)=164.93033d0
       else if (names(i).eq.'IN')then
        am(i)=114.818d0
       else if (names(i).eq.'IR')then
        am(i)=192.217d0
       else if (names(i).eq.'LA')then
        am(i)=138.90547d0
       else if (names(i).eq.'LU')then
        am(i)=174.9668d0
       else if (names(i).eq.'MO')then
        am(i)=95.95d0
       else if (names(i).eq.'ND')then
        am(i)=144.242d0
       else if (names(i).eq.'NB')then
        am(i)=92.90637d0
       else if (names(i).eq.'OS')then
        am(i)=190.23d0
       else if (names(i).eq.'PD')then
        am(i)=106.42d0
       else if (names(i).eq.'PR')then
        am(i)=140.90766d0
       else if (names(i).eq.'PA')then
        am(i)=231.03588d0
       else if (names(i).eq.'RE')then
        am(i)=186.207d0
       else if (names(i).eq.'RH')then
        am(i)=102.90550d0
       else if (names(i).eq.'RB')then
        am(i)=85.4678d0
       else if (names(i).eq.'RU')then
        am(i)=101.07d0
       else if (names(i).eq.'SM')then
        am(i)=150.36d0
       else if (names(i).eq.'SC')then
        am(i)=44.955908d0
       else if (names(i).eq.'SR')then
        am(i)=87.62d0
       else if (names(i).eq.'TA')then
        am(i)=180.94788d0
       else if (names(i).eq.'TB')then
        am(i)=158.92535d0
       else if (names(i).eq.'TH')then
        am(i)=232.0377d0
       else if (names(i).eq.'TM')then
        am(i)=168.93422d0
       else if (names(i).eq.'W')then
        am(i)=183.84d0
       else if (names(i).eq.'YB')then
        am(i)=173.054d0
       else if (names(i).eq.'Y')then
        am(i)=88.90584d0
       else if (names(i).eq.'ZR')then
        am(i)=91.224d0
       else
        write(*,*)'Unknown atom.',names(i),'Exiting..'
        stop 1
       endif
      enddo

      do i=1,natom
       am(i)=am(i)*mu
      enddo
   end subroutine

end module


program MakeRestart
   use mod_restart
   integer :: i,natom,nstate,istate, natom2
   character(len=CHARLENGTH) :: chcoords, chveloc
   logical :: lwig

   call get_inputparams(chcoords, chveloc, istate, nstate, natom, lwig)
      
   if (.not.lwig)then

      open(103,file=chcoords,status='old', action="read")
      read(103,*)natom
      call alloc(natom)

      read(103,*)
      do i=1,natom
       read(103,*)atom(i), x(i), y(i), z(i)
      enddo
      close(103)

      open(103,file=chveloc,status='old', action="read")
      read(103,*)
      do i=1,natom
       read(103,*)vx(i), vy(i), vz(i)
      enddo
      close(103)

   end if

   if (lwig)then

      ! First read natom and atom names from Geometry.dat
      open(100, file=chcoords, action="read", status="old")
      read(100,*)
      read(100,*)natom
      call alloc(natom)
      do i=1, natom
         ! coordinates are rewritten later on
         read(100,*)atom(i),x(i), y(i), z(i)
      end do
      close(100)

      ! Read Wigner data, expecting atomic units
      open(100, file=chveloc, action="read", status="old")
      read(100,*)time,(xwig(i),i=1,3*natom),(p(i),i=1,3*natom)
      close(100)

      call mass_init(natom, atom, mass) !mass in atomic units

      ipom=0
      do i=1,natom
         x(i)=xwig(1+ipom)/ANG
         y(i)=xwig(2+ipom)/ANG
         z(i)=xwig(3+ipom)/ANG
         vx(i)=p(1+ipom)/mass(i)
         vy(i)=p(2+ipom)/mass(i)
         vz(i)=p(3+ipom)/mass(i)
         ipom=ipom+3
      end do
       
   end if

      open(201,file='restart.xyz', action="write", status="new")
      open(202,file='mini.dat', action="write", status="new")

      write(201,*)0
      write(201,*)' Cartesian Coordinates [au]'
      do i=1,natom
         write(201,20)x(i)*ANG,y(i)*ANG,z(i)*ANG
      enddo
      write(201,*)' Cartesian Velocities [au]'
      do i=1,natom
         write(201,20)vx(i), vy(i), vz(i)
      enddo
      if(nstate.gt.1)then
       write(201,*)' Coefficients for SH'
       write(201,*)istate
       do i=1,nstate
        if (i.eq.istate) then
         write(201,*)'1.000000000000000E+000  0.000000000000000E+000'
        else
         write(201,*)'0.000000000000000E+000  0.000000000000000E+000'
        endif
       enddo
      endif
      write(201,*)' Cumulative averages of various estimators'
      write(201,*)'0.000000000000000E+000'
      write(201,*)'0.000000000000000E+000  0.000000000000000E+000'
      write(201,*)'0.000000000000000E+000'
20    format(3E18.10E2)

      write(202,*)natom
      write(202,'(A, A)')'Cartesian Coordinates from:', chcoords
      do i=1,natom
         write(202,30)atom(i),x(i),y(i),z(i)
      enddo

30    format(A,3E18.10E2)
      close(201)
      close(202)
   end



   subroutine get_inputparams(chcoords, chveloc, istate, nstate, natom, lwig)
   use mod_restart, only: charlength
   implicit none
   integer :: istate, nstate, natom
   character(len=CHARLENGTH) :: chcoords, chveloc
   character(len=CHARLENGTH) :: arg
   character(len=4) :: chmode
   integer            :: i
   logical  :: lwig, lex


   if (command_argument_count().ne.5)then
      write(*,*)"Error: wrong number of arguments"
      call PrintHelp()
   end if

   call get_command_argument(1, chmode)
   if (chmode.eq.'-wig')then
      lwig=.true.
   else if(chmode.eq.'-mov')then
      lwig=.false.
   else
      write(*,*)'Error in makerestart: incorrect commandline parameter.'
      call PrintHelp()
   end if

   call get_command_argument(2, arg)
   read(arg,'(A)')chcoords  
   inquire(file=chcoords, exist=lex)
   if(.not.lex)then
      write(*,*)'make_restart: File does not exist!',chcoords
      stop 1
   end if

   call get_command_argument(3, arg)
   read(arg,'(A)')chveloc
   inquire(file=chveloc, exist=lex)
   if(.not.lex)then
      write(*,*)'make_restart: File does not exist!',chveloc
      stop 1
   end if

   call get_command_argument(4, arg)
   read(arg,*)nstate
   if (nstate.lt.0)then
      write(*,*)'makerestart: Number of states must be positive.'
      call PrintHelp()
      stop 1
   end if

   call get_command_argument(5, arg)
   read(arg,'(I3)')istate
   if (istate.lt.0.or.istate.gt.nstate)then
      write(*,*)'makerestart: Invalid initial state.'
      call PrintHelp()
   end if

   end subroutine 

subroutine PrintHelp()
   implicit none
   print '(a)', 'Program for creating ABIN restart files.'
   print '(a)', 'Call as either: '
   print '(a)', '1) ./make_restart -mov coords.xyz veloc.dat nstate istate_init'
   print '(a)', 'or '
   print '(a)', '2) ./make_restart -wig FMSINPOUT/Geometry.dat FMSTRAJS/Traj.xx nstate istate_init'
   stop 1
end subroutine PrintHelp
