codecov:
  require_ci_to_pass: yes
  notify:
    # Send report to Github PR only after all CIs
    # are completed, otherwise we'll temporarily receive
    # incomplete coverage reports.
    # Note that unit test coverage builds count towards the build count!
    after_n_builds: 16
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...95"
  status:
    project:
      # https://docs.codecov.io/docs/commit-status
      default:
        target: auto
        # Allow coverage drop by x%
        threshold: 0.5%
        flags:
          - unittests
    patch:
      default:
        target: 80%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
