#!/bin/bash
#
source SetEnvironment.sh TERAdev

MPIRUN="/home/hollas/programes/mpich-3.1.3/arch/x86_64-intel_2013.2.146/bin/mpirun -np 1 "
ABINEXE=./abin.mpi

rm -f port.txt

$MPIRUN $TERAEXE --inputfile=tera.inp --UseMPI --MPIPort=teraport > tera.out &
sleep 3
# Get PID of the last process
terapid=$!
# Ugly workaround becouse MPI_Lookup does not work
grep port_name: tera.out | awk '{print $6}' > port.txt

$MPIRUN $ABINEXE  &> abin.out &
abinpid=$!
# For DEBUG PURPOSES
#$MPIRUN gdb $ABINEXE 

while true;do
   sleep 2
   if ! `ps|grep -q $terapid` && ! `ps|grep -q $abinpid` ;then
      echo "Both ABIN and TeraChem ended. "
      break
   fi
   if ! `ps|grep -q $terapid` ;then
      echo "Terachem died. Killing ABIN."
      kill -9 $abinpid 
      break
   fi   
   if ! `ps|grep -q $abinpid` ;then
      echo "ABIN died. Killing TeraChem."
      kill -9 $terapid 
      break
   fi
done

